language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - rbx-19mode

gemfile:
  - Gemfile.old
  - Gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode

notifications:
  email: false
